version: 1.0.{build}
skip_branch_with_pr: true
environment:
  DOCKER_USER:
    secure: 5kpGjfjrd0dX7wF+GF3YRF7O0NHoHjXIHZDcnjAuF/0=
  DOCKER_PASS:
    secure: qUYXocrsiTOsLkPTFJODDQ==
image: ubuntu
install:
   - docker version
branches:
  only:
   - master
build_script:
- sh: ./build.sh
test: off