version: 1.0.{build}
environment:
  DOCKER_USER:
    secure: 5kpGjfjrd0dX7wF+GF3YRF7O0NHoHjXIHZDcnjAuF/0=
  DOCKER_PASS:
    secure: qUYXocrsiTOsLkPTFJODDQ==
image: ubuntu
install:
   - docker
branches:
  only:
   - master
build_script:
- sh: .\Build.ps1
test: off